---
title: "A_E1"
output: html_notebook
---

```{r}
ffile <- "A_E1"
# delete existing files first
if (file.exists("A_E1.o"))   file.remove("A_E1.o")
if (file.exists("A_E1.dll")) file.remove("A_E1.dll")
if (file.exists("A_E1.so"))  file.remove("A_E1.so")

# now, compile
system("R CMD SHLIB A_E1.f")
```


```{r}
# this loads the library in any system, Windows or Linux
dyn.load(paste("A_E1", .Platform$dynlib.ext, sep = ""))
```


## Test the function
We call this function with:
```{r}
EI <- function(x) {
  # R function that calls the Fortran function `A_E1` through a Fortran wrapper.
  out <- .Fortran('A_E1_SUB',         # `out` is a list and returns the result
                  n = as.double(x),       # and the parameter that were passed.
                  result = as.double(1))
  return(out$result)             
}

# call the R function wrapper
x <- seq(0, 2.5, 0.01)
Ei <- sapply(x, EI)
Eu <- sapply(x, function(x) log(1/(exp(0.577216)*x)))
df <- data.frame(x, Ei, Eu)
df  
```

```{r}
x <- seq(0, 2.5, 0.01)
Ei <- sapply(x, EI)
Eu <- sapply(x, function(x) log(1/(exp(0.577216)*x)))
df <- data.frame(x, Ei, Eu)
df
```

```{r fig.asp=1}
library(ggplot2)
# add the line for Ei
ggplot(df, aes(x = x, y = Ei)) + geom_line(col="blue") + 
  geom_line(aes(x=x, y=Eu), linetype = "dotted") + ylab("Ei(x)") +
  # annotate Ei
    annotate("text", x = 0.8, y = 2, parse = TRUE, 
           label = "Ei(x)", size=5, col = "blue", fontface = "bold") + 
  # add an arrow to Ei curve
  geom_segment(aes(x = 0.75, y = 1.9, 
                   xend = 0.3, yend = 1.0), 
               colour='gray', 
               size=0.1,  
               arrow = arrow(length = unit(0.5, "cm"))) + 
  # annotate gamma
  annotate("text", x = 1.4, y = 1.3, parse = TRUE,
           label = "gamma==0.577216 ", angle=0, size=3, 
                colour='black') +
  # annotate the function ln(1/e^gamma*x)
  annotate("text", x = 1.1, y = 1.2, parse = TRUE, 
           label = "ln(frac(1, e^{gamma} * x))", size=4) + 
  # add the arrow for ln function
  geom_segment(aes(x = 1, y = 1, 
                   xend = 0.55, yend = 0.0), 
               colour='gray', 
               size=0.3,  
               arrow = arrow(length = unit(0.5, "cm")))

```


## Unload the Fortran subroutine. Generic OS
```{r}
dyn.unload(paste("A_E1", .Platform$dynlib.ext, sep = ""))
```


