---
title: "R Notebook"
output: html_notebook
---

For the following Fortran subroutine, we will compile and link it to call it from R.

```
c file zvodedll.f
      SUBROUTINE FEX (NEQ, T, Y, YDOT, RPAR, IPAR)
      INTEGER NEQ, IPAR(*)
      DOUBLE COMPLEX Y(NEQ), YDOT(NEQ), RPAR(*), CMP
      DOUBLE PRECISION T
      character(len=100) msg
      
c the imaginary unit i
      CMP = DCMPLX(0.0D0,1.0D0)
      
      YDOT(1) = CMP*Y(1)
      YDOT(2) = -CMP*Y(2)*Y(2)*Y(1)
      
      RETURN
      END
      
      SUBROUTINE JEX (NEQ, T, Y, ML, MU, PD, NRPD, RPAR, IPAR)
      INTEGER NEQ, ML, MU, NRPD, IPAR(*)
      DOUBLE COMPLEX Y(NEQ), PD(NRPD,NEQ), RPAR(*), CMP
      DOUBLE PRECISION T
c the imaginary unit i
      CMP = DCMPLX(0.0D0,1.0D0)
      
      PD(2,3) = -2.0D0*CMP*Y(1)*Y(2)
      PD(2,1) = -CMP*Y(2)*Y(2)
      PD(1,1) = CMP
      RETURN
      END
c end of file
    
```    

## Compile
```{r}
# now, compile
system("R CMD SHLIB zvodedll.f")
```

## Load the subroutine. Generic OS call
```{r}
# this loads the library in any system, Windows or Linux
dyn.load(paste("zvodedll", .Platform$dynlib.ext, sep = ""))
```


```{r}
library(deSolve)

#yini <- c(y1 = 1.0, y2 = 0.0, y3 = 0.0)
#times <- c(0, 0.4*10^(0:11) )

outF <- zvode(func = "fex", jacfunc = "jex", y = yini, parms = NULL,
times = times, atol = 1e-10, rtol = 1e-10, dllname = "zvodedll",
initfunc = NULL)
```

## Unload the Fortran subroutine. Generic OS
```{r}
dyn.unload(paste("zvodedll", .Platform$dynlib.ext, sep = ""))
```

